repos:
    - repo: https://github.com/python/black
      rev: stable
      hooks:
      - id: black
        language_version: python3
    - repo: https://github.com/asottile/seed-isort-config
      rev: v1.9.3
      hooks:
      - id: seed-isort-config
        language_version: python3
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
      - id: isort
        language_version: python3
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.8
      hooks:
      - id: flake8
        language_version: python3
