version: '3'

services:
    bce-db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        networks:
            - bce-api-network
    bce-server:
        build:
            context: ./bce-server/
            dockerfile: Dockerfile
        networks:
            - bce-api-network
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./bce-server:/var/app
        ports:
            - "8000:8000"
    bce-ui:
        build:
            context: ./bce-vue-ui/
            dockerfile: Dockerfile
        networks:
            - bce-api-network
        command: yarn run serve
        volumes:
            - ./bce-vue-ui:/var/app
            - node_modules:/var/app/node_modules
        ports:
            - "8080:8080"
        links:
            - bce-server
volumes:
    node_modules:

networks:
    bce-api-network:
