version: "3"

services:
  bce-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - api-network
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    networks:
      - api-network
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/var/app
    ports:
      - "8000:8000"
  ui:
    build:
      context: ./ui/
      dockerfile: Dockerfile
    networks:
      - api-network
    command: yarn run serve
    volumes:
      - ./ui:/var/app
      - node_modules:/var/app/node_modules
    ports:
      - "8080:8080"
    links:
      - server
volumes:
  node_modules:

networks:
  api-network:
