# Generated by Django 2.1.3 on 2018-11-16 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="FieldOption",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("choice", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FieldType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("tooltip", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text Field"),
                            ("TEXTAREA", "Text Area"),
                            ("DATE", "Date"),
                            ("DATETIME", "Date and Time"),
                            ("NUMBER", "Numbers"),
                            ("CURRENCY", "Currency"),
                            ("RADIO", "Radio Buttons"),
                            ("DROPDOWN", "Dropdown Selection"),
                        ],
                        default="TEXT",
                        max_length=10,
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                ("hidden", models.BooleanField(default=False)),
                ("required", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RiskType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField()),
                ("tooltip", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="fieldtype",
            name="risk_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="fields", to="bce.RiskType"
            ),
        ),
        migrations.AddField(
            model_name="fieldoption",
            name="field_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="options", to="bce.FieldType"
            ),
        ),
    ]
