FIELD_TYPE_TEXT = "TEXT"
FIELD_TYPE_TEXTAREA = "TEXTAREA"
FIELD_TYPE_EMAIL = "EMAIL"
FIELD_TYPE_DATE = "DATE"
FIELD_TYPE_DATETIME = "DATETIME"
FIELD_TYPE_NUMBER = "NUMBER"
FIELD_TYPE_CURRENCY = "CURRENCY"
FIELD_TYPE_RADIO = "RADIO"
FIELD_TYPE_DROPDOWN = "DROPDOWN"

DEFAULT_FIELD_TYPES = (
    (FIELD_TYPE_TEXT, "Text Field"),
    (FIELD_TYPE_TEXTAREA, "Text Area"),
    (FIELD_TYPE_EMAIL, "Email Address"),
    (FIELD_TYPE_DATE, "Date"),
    (FIELD_TYPE_DATETIME, "Date and Time"),
    (FIELD_TYPE_NUMBER, "Numbers"),
    (FIELD_TYPE_CURRENCY, "Currency"),
    (FIELD_TYPE_RADIO, "Radio Buttons"),
    (FIELD_TYPE_DROPDOWN, "Dropdown Selection"),
)
