# Generated by Django 3.0.3 on 2020-03-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bce", "0005_auto_20181121_1622"),
    ]

    operations = [
        migrations.AlterModelOptions(name="risktype", options={"ordering": ("-created",)},),
    ]
